In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [20]:
device = torch.device("cuda")

In [21]:
x = torch.rand(5,3)
print(x.size())
print(x)

torch.Size([5, 3])
tensor([[0.2073, 0.1517, 0.6508],
        [0.7279, 0.0992, 0.3831],
        [0.6183, 0.1906, 0.2472],
        [0.6170, 0.1263, 0.6757],
        [0.5643, 0.5060, 0.2318]])


### Send tensor to device

In [22]:
x = x.to(device=device)
print(x)

tensor([[0.2073, 0.1517, 0.6508],
        [0.7279, 0.0992, 0.3831],
        [0.6183, 0.1906, 0.2472],
        [0.6170, 0.1263, 0.6757],
        [0.5643, 0.5060, 0.2318]], device='cuda:0')


In [23]:
class one_layer_net(nn.Module):
    def __init__(self, input_size, output_size):
        super(one_layer_net, self).__init__()
        self.linear_layer = nn.Linear(input_size, output_size, bias=False)
    def forward(self, x):
        return self.linear_layer(x)

In [24]:
net = one_layer_net(5,2)
net = net.to(device)
print(net.linear_layer.weight)

Parameter containing:
tensor([[ 0.0100,  0.2764,  0.2664, -0.3134, -0.1635],
        [ 0.1242, -0.1062,  0.3465, -0.4144,  0.4085]], device='cuda:0',
       requires_grad=True)
